### ISSUE TITLE
Reconciler retries may conflict with later upserts

### ISSUE THREAD

**Issue by gandro** [cilium/statedb#55]
Consider the following sequence of events issued by the reconciler, with `Update` and `Delete` being the `interface Operations` method being invoked by the reconciler for some StateDB object X:

- revision 1: `Update(X)` :heavy_check_mark: 
- revision 2: `Delete(X)` :x: - added to retry-queue
- revision 3: `Update(X)` :heavy_check_mark: 
- retry of revision 2: `Delete(X)` :heavy_check_mark: 

This will result in object `X` being deleted downstream, even though the expect outcome of the upstream sequence `Upsert, Delete, Upsert` is for `X` to be present.

Discovered with @bimmlerd

**Comment by bimmlerd** [comment]
Similar to https://github.com/cilium/cilium/pull/27340

**Comment by bimmlerd** [comment]
I think we missed that this is actually handled - see https://github.com/cilium/statedb/blob/main/reconciler/incremental.go#L126
